### ISSUE TITLE
Incompatibility with Kafka v3.0+

### ISSUE THREAD

**Issue by iMajna** [anderseknert/opa-kafka-plugin#39]
Hi everyone, 

Im having dependency issue while trying to run this setup.

- OPA version: 0.35+
- Kafka version: 3.X
- Opa Kafka plugin version: 1.4.0

```
[2022-03-05 17:41:58,778] ERROR [KafkaApi-2] Unexpected error handling request RequestHeader(apiKey=UPDATE_METADATA, apiVersion=7, clientId=2, correlationId=0) -- UpdateMetadataRequestData(controllerId=2, controllerEpoch=3, brokerEpoch=276, ungroupedPartitionStates=[], topicStates=[], liveBrokers=[UpdateMetadataBroker(id=2, v0Host='', v0Port=0, endpoints=[UpdateMetadataEndpoint(port=9093, host='kafka', listener='CLIENT', securityProtocol=2), UpdateMetadataEndpoint(port=9092, host='kafka', listener='OUTSIDE', securityProtocol=1)], rack=null)]) with context RequestContext(header=RequestHeader(apiKey=UPDATE_METADATA, apiVersion=7, clientId=2, correlationId=0), connectionId='127.0.0.1:9092-127.0.0.1:51473-0', clientAddress=/127.0.0.1, principal=User:ANONYMOUS, listenerName=ListenerName(OUTSIDE), securityProtocol=SSL, clientInformation=ClientInformation(softwareName=unknown, softwareVersion=unknown), fromPrivilegedListener=true, principalSerde=Optional[org.apache.kafka.common.security.authenticator.DefaultKafkaPrincipalBuilder@2caf3347]) (kafka.server.KafkaApis)
com.google.common.util.concurrent.ExecutionError: java.lang.ExceptionInInitializerError
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4848)
	at org.openpolicyagent.kafka.OpaAuthorizer.allowAccess$1(OpaAuthorizer.scala:154)
	at org.openpolicyagent.kafka.OpaAuthorizer.doAuthorize(OpaAuthorizer.scala:165)
	at org.openpolicyagent.kafka.OpaAuthorizer.authorizeAction(OpaAuthorizer.scala:121)
	at org.openpolicyagent.kafka.OpaAuthorizer.$anonfun$authorize$1(OpaAuthorizer.scala:49)
	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:99)
	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:86)
	at scala.collection.convert.JavaCollectionWrappers$JListWrapper.map(JavaCollectionWrappers.scala:103)
	at org.openpolicyagent.kafka.OpaAuthorizer.authorize(OpaAuthorizer.scala:49)
	at kafka.server.AuthHelper.$anonfun$authorize$1(AuthHelper.scala:49)
	at kafka.server.AuthHelper.$anonfun$authorize$1$adapted(AuthHelper.scala:46)
	at scala.Option.forall(Option.scala:420)
	at kafka.server.AuthHelper.authorize(AuthHelper.scala:46)
	at kafka.server.AuthHelper.authorizeClusterOperation(AuthHelper.scala:54)
	at kafka.server.KafkaApis.handleUpdateMetadataRequest(KafkaApis.scala:336)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:175)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:75)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ExceptionInInitializerError
	at org.openpolicyagent.kafka.AllowCallable.call(OpaAuthorizer.scala:271)
	at org.openpolicyagent.kafka.AllowCallable.call(OpaAuthorizer.scala:268)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4853)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 19 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.10.5 requires Jackson Databind version >= 2.10.0 and < 2.11.0
	at com.fasterxml.jackson.module.scala.JacksonModule.setupModule(JacksonModule.scala:61)
	at com.fasterxml.jackson.module.scala.JacksonModule.setupModule$(JacksonModule.scala:46)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:17)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:835)
	at com.fasterxml.jackson.databind.cfg.MapperBuilder.addModule(MapperBuilder.java:243)
	at org.openpolicyagent.kafka.AllowCallable$.<clinit>(OpaAuthorizer.scala:264)
	... 26 more
```
Immediately after this error broker of course shuts down. In case logs are necessary let me know. 
Good thing to mention is that there are no issues on version below 3.0.

Not sure whether you encountered it within testing.

**Comment by anderseknert** [comment]
Hey Ivan! And thanks for reporting this. Yeah, I think we're just lagging behind here. Not sure if it's possible to support 3.0+ while also keeping compatibility backwards, but given this plugin is pretty stable by now, perhaps we could just let the current version(s) be the alternative for 2.x versions, and bump the next release to work with 3.x. Thoughts, @scholzj ?

**Comment by iMajna** [comment]
Aloha :) 
Reason Im reporting this is because I think I saw in some releases before (think v1.2.0 but I might be wrong) a note where it says that compatibility with v3.0 has been introduced :O

**Comment by scholzj** [comment]
As far as I know it works fine with Kafka 3.x -> at least I did not had any issues and its passing our system tests in Strimzi. You need to make sure to pull in the right libraries to not cause conflicts with the libraries already in Kafka. In Strimzi, we normally exclude bunch of them:

```xml
        <dependency>
            <groupId>org.openpolicyagent.kafka</groupId>
            <artifactId>opa-authorizer</artifactId>
            <version>${opa-authorizer.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.fasterxml.jackson.module</groupId>
                    <artifactId>jackson-module-scala_2.13</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.kafka</groupId>
                    <artifactId>kafka_2.13</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.google.code.findbugs</groupId>
                    <artifactId>jsr305</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by anderseknert** [comment]
That's useful, Jakub! Might be a good idea to provide a release jar for 3.x as well still, to allow downloading the plugin as-is. Next week looks pretty busy, but I'll see if I can get around to it.

**Comment by scholzj** [comment]
@anderseknert I wonder if the right solution is to mark these dependencies as provided -> It needs Guava, but `jackson-module-scala_2.13` and obviously also `kafka_2.13` are part of the Kafka distro where the authorizer JAR is copied.

**Comment by scholzj** [comment]
That said, as a Maven user who rarely uses Gradle, I have no clue how to do it.

**Comment by scholzj** [comment]
I spent some time looking at this and opened a PR which should fix it. @iMajna if you have time it would be great if you can doublecheck if it addresses your issue.

**Comment by iMajna** [comment]
I figured I left only emoji instead of a comment, my apologise :S. 

Yeap, it fixes the issue, thanks a lot! :)
